# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20170328_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_app.Artist', unique=True),
        ),
    ]
